[package]
name = "gluesql_rs"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "gluesql_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
gluesql-core = "0.14.0"
rustler = "0.30.0"
